chore/refactor-list-and-sort
raae/nattermob.dev pull request #29
Opened 2021-06-03 06:51 UTC by PaulieScanlon

- change `maxResults` and `q` in YouTube request
- add timestamp `formatString`
- add `index` to list + `#`
- add `formatString` to `publishedAd` for `index.js` and `{youTube.slug}.js`

**Feedback required on**
- add GraphQL filter to hide "upcoming" shows

2021-06-03 06:52 UTC, PaulieScanlon commented on src/pages/index.js
> +        filter: { snippet: { liveBroadcastContent: { ne: "upcoming" } } }
@raae  Do you want to filter out all the upcoming shows. I think this will show the live one when we're on stream it just hides all the others -- unless you think that's good to have in the list?

2021-06-03 06:54 UTC, PaulieScanlon commented
@raae i've changed `Seo.js` to `seo.js` so if we merge this you might have to double-check on your local file system that the case is correct because because Git might not pick up the change + the paths to the component have now changed to be lowercase. -- it's for this reason CamelCase is not good for file and dir names

2021-06-03 06:54 UTC, PaulieScanlon commented
-- also i think the build is failing because i've messed with the cache again. We might need to trigger + clean after this is merged

2021-06-04 05:24 UTC, raae requested changes

2021-06-04 05:24 UTC, raae commented on src/pages/index.js
> +        filter: { snippet: { liveBroadcastContent: { ne: "upcoming" } } }
Remove this and I will approve so we can merge it in.

2021-06-04 05:28 UTC, raae commented on gatsby-node.js
> +    q: "#Nattermob #GatsbyJS Deep Dive Dives",
I think this string is the best " · #GatsbyJS Deep Dive" I end the title for all of them with that, or "Part of "Gatsby Deep Dives with Queen Raae and the Nattermob Pirates". Both #Gatsby and #Nattermob could be present in other videos.

2021-06-04 09:56 UTC, merged