First stab at live now
raae/nattermob.dev pull request #33
Opened 2021-06-04 18:47 UTC by raae

2021-06-09 11:18 UTC, PaulieScanlon commented on src/components/live-now-badge.js
> +      {isMounted ? (
I watched Fredrik Jensen at React Day Norway who suggested doing an `isMounted` state hook so the component only renders once the component has mounted / once the site has hydrated meaning the client and server html will match because this component returns `null` until the `useEffect` kicks in and sets `isMounted` to true

2021-06-09 19:15 UTC, raae commented on src/components/live-now-badge.js
> +      {isMounted ? (
Cool, I have solved this before by having a isSSR prop I pass in to the component since I know this when wrapping the page in `gatsby-ssr.js` and `gatsby-browser.js`. But I guess this solution would work even if use by a layout component etc.

2021-06-09 19:27 UTC, PaulieScanlon commented on src/components/live-now-badge.js
> +      {isMounted ? (
I think the idea behind this might be to eventually abstract the `isMounted` thing into a hook so it can be re-used around the app. Worry about that another time i guess

2021-06-11 12:16 UTC, PaulieScanlon requested changes

2021-06-11 13:17 UTC, raae commented on .env.example
> +GOOGLE_API_KEY_SERVER=
Correct!

2021-06-11 20:13 UTC, merged